package com.pxg.app.core.mapper.appmapper;

import com.pxg.app.core.model.kettle.KettleDatabaseType;

import java.util.List;

public interface KettleDatabaseTypeMapper {
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table kettle.kettle_database_type
//     *
//     * @mbg.generated Thu Sep 26 21:23:20 GMT+08:00 2019
//     */
//    int insert(KettleDatabaseType record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table kettle.kettle_database_type
//     *
//     * @mbg.generated Thu Sep 26 21:23:20 GMT+08:00 2019
//     */
//    int insertSelective(KettleDatabaseType record);

    /**
     * 有条件的查询 数据库类型
     * @param kettleDatabaseType
     * @return
     */
    List<KettleDatabaseType> selectSelective(KettleDatabaseType kettleDatabaseType);
}