package com.pxg.app.core.mapper.appmapper;

import com.pxg.app.core.model.kettle.KettleRepositoryTable;

import java.util.List;

public interface KettleRepositoryTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kettle.kettle_repository_table
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kettle.kettle_repository_table
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    int insert(KettleRepositoryTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kettle.kettle_repository_table
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    int insertSelective(KettleRepositoryTable record);

    /**
     * 根据条件查询
     */
    List<KettleRepositoryTable> selectSelective(KettleRepositoryTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kettle.kettle_repository_table
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    KettleRepositoryTable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kettle.kettle_repository_table
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(KettleRepositoryTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kettle.kettle_repository_table
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    int updateByPrimaryKey(KettleRepositoryTable record);
}