package com.pxg.app.core.mapper.appmapper;

import com.pxg.app.core.model.klog.LogInfo;

public interface LogInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applog.log_info
     * @mbg.generated Fri Nov 01 14:44:04 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer klogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applog.log_info
     * @mbg.generated Fri Nov 01 14:44:04 GMT+08:00 2019
     */
    int insert(LogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applog.log_info
     * @mbg.generated Fri Nov 01 14:44:04 GMT+08:00 2019
     */
    int insertSelective(LogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applog.log_info
     * @mbg.generated Fri Nov 01 14:44:04 GMT+08:00 2019
     */
    LogInfo selectByPrimaryKey(Integer klogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applog.log_info
     * @mbg.generated Fri Nov 01 14:44:04 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(LogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applog.log_info
     * @mbg.generated Fri Nov 01 14:44:04 GMT+08:00 2019
     */
    int updateByPrimaryKey(LogInfo record);
}