package com.pxg.app.core.mapper.appmapper;

import com.pxg.app.core.model.kmmail.MailInfo;

import java.util.List;

public interface MailInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table km_mail.mail_info
     * @mbg.generated Fri Oct 18 16:37:38 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table km_mail.mail_info
     * @mbg.generated Fri Oct 18 16:37:38 GMT+08:00 2019
     */
    int insert(MailInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table km_mail.mail_info
     * @mbg.generated Fri Oct 18 16:37:38 GMT+08:00 2019
     */
    int insertSelective(MailInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table km_mail.mail_info
     * @mbg.generated Fri Oct 18 16:37:38 GMT+08:00 2019
     */
    MailInfo selectByPrimaryKey(Integer id);

    List<MailInfo> selectBySelective(MailInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table km_mail.mail_info
     * @mbg.generated Fri Oct 18 16:37:38 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(MailInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table km_mail.mail_info
     * @mbg.generated Fri Oct 18 16:37:38 GMT+08:00 2019
     */
    int updateByPrimaryKey(MailInfo record);
}