package com.pxg.app.core.mapper.appmapper;

import com.pxg.app.core.model.user.PermissionRole;

import java.util.List;

public interface PermissionRoleMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appuser.permission_role
     * @mbg.generated Fri Aug 30 23:16:37 CST 2019
     */
    int insert(PermissionRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appuser.permission_role
     * @mbg.generated Fri Aug 30 23:16:37 CST 2019
     */
    int insertSelective(PermissionRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appuser.permission_role
     * @mbg.generated Fri Aug 30 23:16:37 CST 2019
     */
    PermissionRole selectByPrimaryKey(Integer userId);

    /**
     * 查询用户权限对应表
     * @param record
     * @return
     */
    List<PermissionRole> selectSelective(PermissionRole record);

    Long count(PermissionRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appuser.permission_role
     * @mbg.generated Fri Aug 30 23:16:37 CST 2019
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appuser.permission_role
     * @mbg.generated Fri Aug 30 23:16:37 CST 2019
     */
    int updateByPrimaryKey(PermissionRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appuser.permission_role
     * @mbg.generated Fri Aug 30 23:16:37 CST 2019
     */
    int updateByPrimaryKeySelective(PermissionRole record);


}