package com.pxg.app.core.mapper.appmapper;

import com.pxg.app.core.model.klog.ServerLogInfo;

public interface ServerLogInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applog.server_log_info
     * @mbg.generated Fri Nov 08 11:12:40 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applog.server_log_info
     * @mbg.generated Fri Nov 08 11:12:40 GMT+08:00 2019
     */
    int insert(ServerLogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applog.server_log_info
     * @mbg.generated Fri Nov 08 11:12:40 GMT+08:00 2019
     */
    int insertSelective(ServerLogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applog.server_log_info
     * @mbg.generated Fri Nov 08 11:12:40 GMT+08:00 2019
     */
    ServerLogInfo selectByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applog.server_log_info
     * @mbg.generated Fri Nov 08 11:12:40 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(ServerLogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applog.server_log_info
     * @mbg.generated Fri Nov 08 11:12:40 GMT+08:00 2019
     */
    int updateByPrimaryKey(ServerLogInfo record);
}