package com.pxg.app.core.mapper.appmapper;

import com.pxg.app.core.model.task.TaskCron;

import java.util.List;

public interface TaskCronMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task.task_cron
     * @mbg.generated Sat Sep 07 10:37:57 CST 2019
     */
    int insert(TaskCron record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task.task_cron
     * @mbg.generated Sat Sep 07 10:37:57 CST 2019
     */
    int insertSelective(TaskCron record);

    List<TaskCron> selectSelective(TaskCron record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task.task_cron
     * @mbg.generated Sat Sep 07 10:37:57 CST 2019
     */
    TaskCron selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task.task_cron
     * @mbg.generated Sat Sep 07 10:37:57 CST 2019
     */
    int updateByPrimaryKeySelective(TaskCron record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task.task_cron
     * @mbg.generated Sat Sep 07 10:37:57 CST 2019
     */
    int updateByPrimaryKey(TaskCron record);
}