package com.pxg.app.core.mapper.appmapper;

import com.pxg.app.core.model.task.TaskQuartzSet;

import java.util.List;

public interface TaskQuartzSetMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table km_task.task_quartz_set
     * @mbg.generated Fri Sep 06 18:17:47 CST 2019
     */
    long count(TaskQuartzSet record);


    //不提供删除

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table km_task.task_quartz_set
     * @mbg.generated Fri Sep 06 18:17:47 CST 2019
     */
    int insert(TaskQuartzSet record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table km_task.task_quartz_set
     * @mbg.generated Fri Sep 06 18:17:47 CST 2019
     */
    int insertSelective(TaskQuartzSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table km_task.task_quartz_set
     * @mbg.generated Fri Sep 06 18:17:47 CST 2019
     */
    List<TaskQuartzSet> select(TaskQuartzSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table km_task.task_quartz_set
     * @mbg.generated Fri Sep 06 18:17:47 CST 2019
     */
    TaskQuartzSet selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table km_task.task_quartz_set
     * @mbg.generated Fri Sep 06 18:17:47 CST 2019
     */
    int updateSelective(TaskQuartzSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table km_task.task_quartz_set
     * @mbg.generated Fri Sep 06 18:17:47 CST 2019
     */
    int updateByPrimaryKeySelective(TaskQuartzSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table km_task.task_quartz_set
     * @mbg.generated Fri Sep 06 18:17:47 CST 2019
     */
    int updateByPrimaryKey(TaskQuartzSet record);
}