package com.pxg.app.core.mapper.appmapper;

import com.pxg.app.core.model.task.TaskQuartzSet;

import java.util.List;

public interface TaskQuartzSetMapper {


    List<TaskQuartzSet> selectSelective(TaskQuartzSet record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table km_task.task_quartz_set
     *
     * @mbg.generated Sat Nov 02 17:03:41 GMT+08:00 2019
     */
    int insert(TaskQuartzSet record);


    boolean addRunTimes(TaskQuartzSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table km_task.task_quartz_set
     *
     * @mbg.generated Sat Nov 02 17:03:41 GMT+08:00 2019
     */
    TaskQuartzSet selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table km_task.task_quartz_set
     *
     * @mbg.generated Sat Nov 02 17:03:41 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(TaskQuartzSet record);

}