package com.pxg.app.core.mapper.appmapper;

import com.pxg.app.core.model.monitor.TbMemoryRecord;

public interface TbMemoryRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor.tb_memory_record
     * @mbg.generated Sun Sep 29 19:47:37 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor.tb_memory_record
     * @mbg.generated Sun Sep 29 19:47:37 GMT+08:00 2019
     */
    int insert(TbMemoryRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor.tb_memory_record
     * @mbg.generated Sun Sep 29 19:47:37 GMT+08:00 2019
     */
    int insertSelective(TbMemoryRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor.tb_memory_record
     * @mbg.generated Sun Sep 29 19:47:37 GMT+08:00 2019
     */
    TbMemoryRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor.tb_memory_record
     * @mbg.generated Sun Sep 29 19:47:37 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(TbMemoryRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor.tb_memory_record
     * @mbg.generated Sun Sep 29 19:47:37 GMT+08:00 2019
     */
    int updateByPrimaryKey(TbMemoryRecord record);
}