package com.pxg.app.core.mapper.appmapper;

import com.pxg.app.core.model.user.TbRole;

import java.util.List;

public interface TbRoleMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appuser.tb_role
     * @mbg.generated Fri Aug 30 23:16:37 CST 2019
     */
    int insert(TbRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appuser.tb_role
     * @mbg.generated Fri Aug 30 23:16:37 CST 2019
     */
    int insertSelective(TbRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appuser.tb_role
     * @mbg.generated Fri Aug 30 23:16:37 CST 2019
     */
    long count(TbRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appuser.tb_role
     * @mbg.generated Fri Aug 30 23:16:37 CST 2019
     */
    List<TbRole> selectSelective(TbRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appuser.tb_role
     * @mbg.generated Fri Aug 30 23:16:37 CST 2019
     */
    TbRole selectByPrimaryKey(Integer rid);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appuser.tb_role
     * @mbg.generated Fri Aug 30 23:16:37 CST 2019
     */
    int updateByPrimaryKeySelective(TbRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appuser.tb_role
     * @mbg.generated Fri Aug 30 23:16:37 CST 2019
     */
    int updateByPrimaryKey(TbRole record);
}