package com.pxg.app.core.mapper.appmapper;

import com.pxg.app.core.model.user.TbUser;
import com.pxg.app.core.modelutil.RegistUserModel;

import java.util.List;

public interface TbUserMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appuser.tb_user
     * @mbg.generated Fri Aug 30 23:16:37 CST 2019
     */
    int insert(TbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appuser.tb_user
     * @mbg.generated Fri Aug 30 23:16:37 CST 2019
     */
    int insertSelective(TbUser record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appuser.tb_user
     * @mbg.generated Fri Aug 30 23:16:37 CST 2019
     */
    long count(TbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appuser.tb_user
     * @mbg.generated Fri Aug 30 23:16:37 CST 2019
     */
    TbUser selectByPrimaryKey(Integer id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appuser.tb_user
     * @mbg.generated Fri Aug 30 23:16:37 CST 2019
     */
    List<TbUser> selectSelective(TbUser record);

    List<RegistUserModel> selectUserWithRoleList();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appuser.tb_user
     * @mbg.generated Fri Aug 30 23:16:37 CST 2019
     */
    int updateByPrimaryKeySelective(TbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appuser.tb_user
     * @mbg.generated Fri Aug 30 23:16:37 CST 2019
     */
    int updateByPrimaryKey(TbUser record);
}