package com.pxg.app.core.model.monitor;

import java.io.Serializable;

public class TbMemoryRecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor.tb_memory_record.id
     * @mbg.generated Sun Sep 29 19:47:37 GMT+08:00 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor.tb_memory_record.date_info
     * @mbg.generated Sun Sep 29 19:47:37 GMT+08:00 2019
     */
    private String dateInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor.tb_memory_record.time_info
     * @mbg.generated Sun Sep 29 19:47:37 GMT+08:00 2019
     */
    private String timeInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor.tb_memory_record.total_memory
     * @mbg.generated Sun Sep 29 19:47:37 GMT+08:00 2019
     */
    private Double totalMemory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor.tb_memory_record.used_memory
     * @mbg.generated Sun Sep 29 19:47:37 GMT+08:00 2019
     */
    private Double usedMemory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor.tb_memory_record.free_memory
     * @mbg.generated Sun Sep 29 19:47:37 GMT+08:00 2019
     */
    private Double freeMemory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table monitor.tb_memory_record
     * @mbg.generated Sun Sep 29 19:47:37 GMT+08:00 2019
     */
    private static final long serialVersionUID = 1L;


    @Override
    public String toString() {
        return "TbMemoryRecord{" +
                "id=" + id +
                ", dateInfo='" + dateInfo + '\'' +
                ", timeInfo='" + timeInfo + '\'' +
                ", totalMemory=" + totalMemory +
                ", usedMemory=" + usedMemory +
                ", freeMemory=" + freeMemory +
                '}';
    }

    /**
     * 基本的构造方法
     */
    public TbMemoryRecord() {
    }

    /**
     * 带参数的构造方法
     */
    public TbMemoryRecord(String dateInfo, String timeInfo, Double totalMemory, Double usedMemory, Double freeMemory) {
        this.dateInfo = dateInfo;
        this.timeInfo = timeInfo;
        this.totalMemory = totalMemory;
        this.usedMemory = usedMemory;
        this.freeMemory = freeMemory;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor.tb_memory_record.id
     * @return the value of monitor.tb_memory_record.id
     * @mbg.generated Sun Sep 29 19:47:37 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor.tb_memory_record.id
     * @param id the value for monitor.tb_memory_record.id
     * @mbg.generated Sun Sep 29 19:47:37 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor.tb_memory_record.date_info
     * @return the value of monitor.tb_memory_record.date_info
     * @mbg.generated Sun Sep 29 19:47:37 GMT+08:00 2019
     */
    public String getDateInfo() {
        return dateInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor.tb_memory_record.date_info
     * @param dateInfo the value for monitor.tb_memory_record.date_info
     * @mbg.generated Sun Sep 29 19:47:37 GMT+08:00 2019
     */
    public void setDateInfo(String dateInfo) {
        this.dateInfo = dateInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor.tb_memory_record.time_info
     * @return the value of monitor.tb_memory_record.time_info
     * @mbg.generated Sun Sep 29 19:47:37 GMT+08:00 2019
     */
    public String getTimeInfo() {
        return timeInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor.tb_memory_record.time_info
     * @param timeInfo the value for monitor.tb_memory_record.time_info
     * @mbg.generated Sun Sep 29 19:47:37 GMT+08:00 2019
     */
    public void setTimeInfo(String timeInfo) {
        this.timeInfo = timeInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor.tb_memory_record.total_memory
     * @return the value of monitor.tb_memory_record.total_memory
     * @mbg.generated Sun Sep 29 19:47:37 GMT+08:00 2019
     */
    public Double getTotalMemory() {
        return totalMemory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor.tb_memory_record.total_memory
     * @param totalMemory the value for monitor.tb_memory_record.total_memory
     * @mbg.generated Sun Sep 29 19:47:37 GMT+08:00 2019
     */
    public void setTotalMemory(Double totalMemory) {
        this.totalMemory = totalMemory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor.tb_memory_record.used_memory
     * @return the value of monitor.tb_memory_record.used_memory
     * @mbg.generated Sun Sep 29 19:47:37 GMT+08:00 2019
     */
    public Double getUsedMemory() {
        return usedMemory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor.tb_memory_record.used_memory
     * @param usedMemory the value for monitor.tb_memory_record.used_memory
     * @mbg.generated Sun Sep 29 19:47:37 GMT+08:00 2019
     */
    public void setUsedMemory(Double usedMemory) {
        this.usedMemory = usedMemory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor.tb_memory_record.free_memory
     * @return the value of monitor.tb_memory_record.free_memory
     * @mbg.generated Sun Sep 29 19:47:37 GMT+08:00 2019
     */
    public Double getFreeMemory() {
        return freeMemory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor.tb_memory_record.free_memory
     * @param freeMemory the value for monitor.tb_memory_record.free_memory
     * @mbg.generated Sun Sep 29 19:47:37 GMT+08:00 2019
     */
    public void setFreeMemory(Double freeMemory) {
        this.freeMemory = freeMemory;
    }
}