package com.pxg.app.core.model.user;

import java.io.Serializable;
import java.util.Date;

public class TbUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appuser.tb_user.id
     * @mbg.generated Fri Aug 30 23:16:37 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appuser.tb_user.user_name
     * @mbg.generated Fri Aug 30 23:16:37 CST 2019
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appuser.tb_user.user_password
     * @mbg.generated Fri Aug 30 23:16:37 CST 2019
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appuser.tb_user.create_time
     * @mbg.generated Fri Aug 30 23:16:37 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appuser.tb_user.is_deleted
     * @mbg.generated Fri Aug 30 23:16:37 CST 2019
     */
    private Boolean isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appuser.tb_user.is_locked
     * @mbg.generated Fri Aug 30 23:16:37 CST 2019
     */
    private Boolean isLocked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table appuser.tb_user
     * @mbg.generated Fri Aug 30 23:16:37 CST 2019
     */
    private static final long serialVersionUID = 1L;

    public TbUser() {
    }

    public TbUser(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appuser.tb_user.id
     * @return the value of appuser.tb_user.id
     * @mbg.generated Fri Aug 30 23:16:37 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appuser.tb_user.id
     * @param id the value for appuser.tb_user.id
     * @mbg.generated Fri Aug 30 23:16:37 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appuser.tb_user.user_name
     * @return the value of appuser.tb_user.user_name
     * @mbg.generated Fri Aug 30 23:16:37 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appuser.tb_user.user_name
     * @param userName the value for appuser.tb_user.user_name
     * @mbg.generated Fri Aug 30 23:16:37 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appuser.tb_user.user_password
     * @return the value of appuser.tb_user.user_password
     * @mbg.generated Fri Aug 30 23:16:37 CST 2019
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appuser.tb_user.user_password
     * @param userPassword the value for appuser.tb_user.user_password
     * @mbg.generated Fri Aug 30 23:16:37 CST 2019
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appuser.tb_user.create_time
     * @return the value of appuser.tb_user.create_time
     * @mbg.generated Fri Aug 30 23:16:37 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appuser.tb_user.create_time
     * @param createTime the value for appuser.tb_user.create_time
     * @mbg.generated Fri Aug 30 23:16:37 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appuser.tb_user.is_deleted
     * @return the value of appuser.tb_user.is_deleted
     * @mbg.generated Fri Aug 30 23:16:37 CST 2019
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appuser.tb_user.is_deleted
     * @param isDeleted the value for appuser.tb_user.is_deleted
     * @mbg.generated Fri Aug 30 23:16:37 CST 2019
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appuser.tb_user.is_locked
     * @return the value of appuser.tb_user.is_locked
     * @mbg.generated Fri Aug 30 23:16:37 CST 2019
     */
    public Boolean getIsLocked() {
        return isLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appuser.tb_user.is_locked
     * @param isLocked the value for appuser.tb_user.is_locked
     * @mbg.generated Fri Aug 30 23:16:37 CST 2019
     */
    public void setIsLocked(Boolean isLocked) {
        this.isLocked = isLocked;
    }

    @Override
    public String toString() {
        return "TbUser{" +
                "id=" + id +
                ", userName='" + userName + '\'' +
                ", userPassword='" + userPassword + '\'' +
                ", createTime=" + createTime +
                ", isDeleted=" + isDeleted +
                ", isLocked=" + isLocked +
                '}';
    }
}