package com.pxg.app.core.model.kettle;

import java.io.Serializable;

/**
 * <p>
 * @author pxg
 * @version v1.0.0
 * @date 2019-09-26
 * @email pxg950110@163.com
 * @decription kettle数据库类型
 * </p>
 */
public class KettleDatabaseType implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kettle.kettle_database_type.id_database_type
     * @mbg.generated Thu Sep 26 21:23:20 GMT+08:00 2019
     */
    private Long idDatabaseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kettle.kettle_database_type.code
     * @mbg.generated Thu Sep 26 21:23:20 GMT+08:00 2019
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kettle.kettle_database_type.description
     * @mbg.generated Thu Sep 26 21:23:20 GMT+08:00 2019
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kettle.kettle_database_type.description_text
     * @mbg.generated Thu Sep 26 21:23:20 GMT+08:00 2019
     */
    private String descriptionText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kettle.kettle_database_type
     * @mbg.generated Thu Sep 26 21:23:20 GMT+08:00 2019
     */
    private static final long serialVersionUID = 1L;

    public KettleDatabaseType(Long idDatabaseType) {
        this.idDatabaseType = idDatabaseType;
    }

    public KettleDatabaseType() {
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kettle.kettle_database_type.id_database_type
     * @return the value of kettle.kettle_database_type.id_database_type
     * @mbg.generated Thu Sep 26 21:23:20 GMT+08:00 2019
     */
    public Long getIdDatabaseType() {
        return idDatabaseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kettle.kettle_database_type.id_database_type
     * @param idDatabaseType the value for kettle.kettle_database_type.id_database_type
     * @mbg.generated Thu Sep 26 21:23:20 GMT+08:00 2019
     */
    public void setIdDatabaseType(Long idDatabaseType) {
        this.idDatabaseType = idDatabaseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kettle.kettle_database_type.code
     * @return the value of kettle.kettle_database_type.code
     * @mbg.generated Thu Sep 26 21:23:20 GMT+08:00 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kettle.kettle_database_type.code
     * @param code the value for kettle.kettle_database_type.code
     * @mbg.generated Thu Sep 26 21:23:20 GMT+08:00 2019
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kettle.kettle_database_type.description
     * @return the value of kettle.kettle_database_type.description
     * @mbg.generated Thu Sep 26 21:23:20 GMT+08:00 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kettle.kettle_database_type.description
     * @param description the value for kettle.kettle_database_type.description
     * @mbg.generated Thu Sep 26 21:23:20 GMT+08:00 2019
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kettle.kettle_database_type.description_text
     * @return the value of kettle.kettle_database_type.description_text
     * @mbg.generated Thu Sep 26 21:23:20 GMT+08:00 2019
     */
    public String getDescriptionText() {
        return descriptionText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kettle.kettle_database_type.description_text
     * @param descriptionText the value for kettle.kettle_database_type.description_text
     * @mbg.generated Thu Sep 26 21:23:20 GMT+08:00 2019
     */
    public void setDescriptionText(String descriptionText) {
        this.descriptionText = descriptionText;
    }
}