package com.pxg.app.core.model.kettle;

import com.pxg.app.util.JsonUtils;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.util.Date;

public class KettleRepositoryTable implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kettle.kettle_repository_table.id
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kettle.kettle_repository_table.k_name
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    @ApiModelProperty("资源库名称")
    private String kName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kettle.kettle_repository_table.k_type_id
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    @ApiModelProperty("数据库类型id")
    private Integer kTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kettle.kettle_repository_table.k_type_name
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    @ApiModelProperty("数据库类型名称")
    private String kTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kettle.kettle_repository_table.k_access
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    @ApiModelProperty("数据库")
    private String kAccess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kettle.kettle_repository_table.k_host
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    @ApiModelProperty("数据库地址")
    private String kHost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kettle.kettle_repository_table.k_db
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    @ApiModelProperty("数据库名")
    private String kDb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kettle.kettle_repository_table.k_port
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    @ApiModelProperty("数据库端口")
    private String kPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kettle.kettle_repository_table.k_user
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    @ApiModelProperty("用户名")
    private String kUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kettle.kettle_repository_table.k_pwd
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    @ApiModelProperty("密码")
    private String kPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kettle.kettle_repository_table.status
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    @ApiModelProperty("是否有效")
    // 0 无效 1有效 2 删除
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kettle.kettle_repository_table.create_time
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    @ApiModelProperty("创建时间")
    private Date createTime;

    /**
     * k_rep_user
     * 连接资源库用户名
     */
    @ApiModelProperty("资源库用户名")
    private String kRepUser;

    /**
     * k_rep_password
     * 连接资源库密码 （暂时不加密） 后期考虑加密处理
     */
    @ApiModelProperty("资源库密码")
    private String kRepPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kettle.kettle_repository_table
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    private static final long serialVersionUID = 1L;

    public KettleRepositoryTable() {
    }

    public KettleRepositoryTable(String kTypeName, String kHost, String kDb, String kPort, Integer status) {
        this.kTypeName = kTypeName;
        this.kHost = kHost;
        this.kDb = kDb;
        this.kPort = kPort;
        this.status = status;
    }

    public String getkRepUser() {
        return kRepUser;
    }

    public void setkRepUser(String kRepUser) {
        this.kRepUser = kRepUser;
    }

    public String getkRepPassword() {
        return kRepPassword;
    }

    public void setkRepPassword(String kRepPassword) {
        this.kRepPassword = kRepPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kettle.kettle_repository_table.id
     * @return the value of kettle.kettle_repository_table.id
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kettle.kettle_repository_table.id
     * @param id the value for kettle.kettle_repository_table.id
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kettle.kettle_repository_table.k_name
     * @return the value of kettle.kettle_repository_table.k_name
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    public String getkName() {
        return kName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kettle.kettle_repository_table.k_name
     * @param kName the value for kettle.kettle_repository_table.k_name
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    public void setkName(String kName) {
        this.kName = kName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kettle.kettle_repository_table.k_type_id
     * @return the value of kettle.kettle_repository_table.k_type_id
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    public Integer getkTypeId() {
        return kTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kettle.kettle_repository_table.k_type_id
     * @param kTypeId the value for kettle.kettle_repository_table.k_type_id
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    public void setkTypeId(Integer kTypeId) {
        this.kTypeId = kTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kettle.kettle_repository_table.k_type_name
     * @return the value of kettle.kettle_repository_table.k_type_name
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    public String getkTypeName() {
        return kTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kettle.kettle_repository_table.k_type_name
     * @param kTypeName the value for kettle.kettle_repository_table.k_type_name
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    public void setkTypeName(String kTypeName) {
        this.kTypeName = kTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kettle.kettle_repository_table.k_access
     * @return the value of kettle.kettle_repository_table.k_access
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    public String getkAccess() {
        return kAccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kettle.kettle_repository_table.k_access
     * @param kAccess the value for kettle.kettle_repository_table.k_access
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    public void setkAccess(String kAccess) {
        this.kAccess = kAccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kettle.kettle_repository_table.k_host
     * @return the value of kettle.kettle_repository_table.k_host
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    public String getkHost() {
        return kHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kettle.kettle_repository_table.k_host
     * @param kHost the value for kettle.kettle_repository_table.k_host
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    public void setkHost(String kHost) {
        this.kHost = kHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kettle.kettle_repository_table.k_db
     * @return the value of kettle.kettle_repository_table.k_db
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    public String getkDb() {
        return kDb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kettle.kettle_repository_table.k_db
     * @param kDb the value for kettle.kettle_repository_table.k_db
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    public void setkDb(String kDb) {
        this.kDb = kDb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kettle.kettle_repository_table.k_port
     * @return the value of kettle.kettle_repository_table.k_port
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    public String getkPort() {
        return kPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kettle.kettle_repository_table.k_port
     * @param kPort the value for kettle.kettle_repository_table.k_port
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    public void setkPort(String kPort) {
        this.kPort = kPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kettle.kettle_repository_table.k_user
     * @return the value of kettle.kettle_repository_table.k_user
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    public String getkUser() {
        return kUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kettle.kettle_repository_table.k_user
     * @param kUser the value for kettle.kettle_repository_table.k_user
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    public void setkUser(String kUser) {
        this.kUser = kUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kettle.kettle_repository_table.k_pwd
     * @return the value of kettle.kettle_repository_table.k_pwd
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    public String getkPwd() {
        return kPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kettle.kettle_repository_table.k_pwd
     * @param kPwd the value for kettle.kettle_repository_table.k_pwd
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    public void setkPwd(String kPwd) {
        this.kPwd = kPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kettle.kettle_repository_table.status
     * @return the value of kettle.kettle_repository_table.status
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kettle.kettle_repository_table.status
     * @param status the value for kettle.kettle_repository_table.status
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kettle.kettle_repository_table.create_time
     * @return the value of kettle.kettle_repository_table.create_time
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kettle.kettle_repository_table.create_time
     * @param createTime the value for kettle.kettle_repository_table.create_time
     * @mbg.generated Mon Sep 30 23:28:37 GMT+08:00 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Override
    public String toString() {
        return JsonUtils.ObjectToJSONString(this);
    }
}