package com.pxg.app.core.model.kmmail;

import java.io.Serializable;
import java.util.Date;

public class MailInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column km_mail.mail_info.id
     * @mbg.generated Fri Oct 18 16:37:38 GMT+08:00 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column km_mail.mail_info.mail_url
     * @mbg.generated Fri Oct 18 16:37:38 GMT+08:00 2019
     */
    private String mailUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column km_mail.mail_info.mail_user_id
     * @mbg.generated Fri Oct 18 16:37:38 GMT+08:00 2019
     */
    private Integer mailUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column km_mail.mail_info.status
     * @mbg.generated Fri Oct 18 16:37:38 GMT+08:00 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column km_mail.mail_info.create_time
     * @mbg.generated Fri Oct 18 16:37:38 GMT+08:00 2019
     */
    private Date createTime;


    public MailInfo() {
    }

    public MailInfo(String mailUrl, Integer status) {
        this.mailUrl = mailUrl;
        this.status = status;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table km_mail.mail_info
     * @mbg.generated Fri Oct 18 16:37:38 GMT+08:00 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column km_mail.mail_info.id
     * @return the value of km_mail.mail_info.id
     * @mbg.generated Fri Oct 18 16:37:38 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column km_mail.mail_info.id
     * @param id the value for km_mail.mail_info.id
     * @mbg.generated Fri Oct 18 16:37:38 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column km_mail.mail_info.mail_url
     * @return the value of km_mail.mail_info.mail_url
     * @mbg.generated Fri Oct 18 16:37:38 GMT+08:00 2019
     */
    public String getMailUrl() {
        return mailUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column km_mail.mail_info.mail_url
     * @param mailUrl the value for km_mail.mail_info.mail_url
     * @mbg.generated Fri Oct 18 16:37:38 GMT+08:00 2019
     */
    public void setMailUrl(String mailUrl) {
        this.mailUrl = mailUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column km_mail.mail_info.mail_user_id
     * @return the value of km_mail.mail_info.mail_user_id
     * @mbg.generated Fri Oct 18 16:37:38 GMT+08:00 2019
     */
    public Integer getMailUserId() {
        return mailUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column km_mail.mail_info.mail_user_id
     * @param mailUserId the value for km_mail.mail_info.mail_user_id
     * @mbg.generated Fri Oct 18 16:37:38 GMT+08:00 2019
     */
    public void setMailUserId(Integer mailUserId) {
        this.mailUserId = mailUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column km_mail.mail_info.status
     * @return the value of km_mail.mail_info.status
     * @mbg.generated Fri Oct 18 16:37:38 GMT+08:00 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column km_mail.mail_info.status
     * @param status the value for km_mail.mail_info.status
     * @mbg.generated Fri Oct 18 16:37:38 GMT+08:00 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column km_mail.mail_info.create_time
     * @return the value of km_mail.mail_info.create_time
     * @mbg.generated Fri Oct 18 16:37:38 GMT+08:00 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column km_mail.mail_info.create_time
     * @param createTime the value for km_mail.mail_info.create_time
     * @mbg.generated Fri Oct 18 16:37:38 GMT+08:00 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}