package com.pxg.app.core.model.task;

import java.io.Serializable;
import java.util.Date;

public class TaskQuartzSet implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column km_task.task_quartz_set.id
     *
     * @mbg.generated Sat Nov 02 17:03:41 GMT+08:00 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column km_task.task_quartz_set.job_id
     *
     * @mbg.generated Sat Nov 02 17:03:41 GMT+08:00 2019
     */
    private Integer jobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column km_task.task_quartz_set.job_type
     * @mbg.generated Sat Nov 02 17:03:41 GMT+08:00 2019
     */
    private String jobType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column km_task.task_quartz_set.class_type
     *
     * @mbg.generated Sat Nov 02 17:03:41 GMT+08:00 2019
     */
    private String classType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column km_task.task_quartz_set.start_plan_time
     *
     * @mbg.generated Sat Nov 02 17:03:41 GMT+08:00 2019
     */
    private Date startPlanTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column km_task.task_quartz_set.next_plan_time
     *
     * @mbg.generated Sat Nov 02 17:03:41 GMT+08:00 2019
     */
    private Date nextPlanTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column km_task.task_quartz_set.status
     *
     * @mbg.generated Sat Nov 02 17:03:41 GMT+08:00 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column km_task.task_quartz_set.plan_times
     *
     * @mbg.generated Sat Nov 02 17:03:41 GMT+08:00 2019
     */
    private Integer planTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column km_task.task_quartz_set.create_time
     *
     * @mbg.generated Sat Nov 02 17:03:41 GMT+08:00 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column km_task.task_quartz_set.cron_id
     *
     * @mbg.generated Sat Nov 02 17:03:41 GMT+08:00 2019
     */
    private Integer cronId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column km_task.task_quartz_set.cron_text
     *
     * @mbg.generated Sat Nov 02 17:03:41 GMT+08:00 2019
     */
    private String cronText;

    //repository_id 资源库id
    private Integer repositoryId;

    //是否执行
    private Integer isRun;

    public Integer getIsRun() {
        return isRun;
    }

    public void setIsRun(Integer isRun) {
        this.isRun = isRun;
    }

    public Integer getRepositoryId() {
        return repositoryId;
    }

    public void setRepositoryId(Integer repositoryId) {
        this.repositoryId = repositoryId;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table km_task.task_quartz_set
     *
     * @mbg.generated Sat Nov 02 17:03:41 GMT+08:00 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column km_task.task_quartz_set.id
     *
     * @return the value of km_task.task_quartz_set.id
     *
     * @mbg.generated Sat Nov 02 17:03:41 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column km_task.task_quartz_set.id
     *
     * @param id the value for km_task.task_quartz_set.id
     *
     * @mbg.generated Sat Nov 02 17:03:41 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column km_task.task_quartz_set.job_id
     *
     * @return the value of km_task.task_quartz_set.job_id
     *
     * @mbg.generated Sat Nov 02 17:03:41 GMT+08:00 2019
     */
    public Integer getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column km_task.task_quartz_set.job_id
     *
     * @param jobId the value for km_task.task_quartz_set.job_id
     *
     * @mbg.generated Sat Nov 02 17:03:41 GMT+08:00 2019
     */
    public void setJobId(Integer jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column km_task.task_quartz_set.job_type
     *
     * @return the value of km_task.task_quartz_set.job_type
     *
     * @mbg.generated Sat Nov 02 17:03:41 GMT+08:00 2019
     */
    public String getJobType() {
        return jobType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column km_task.task_quartz_set.job_type
     * @param jobType the value for km_task.task_quartz_set.job_type
     * @mbg.generated Sat Nov 02 17:03:41 GMT+08:00 2019
     */
    public void setJobType(String jobType) {
        this.jobType = jobType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column km_task.task_quartz_set.class_type
     * @return the value of km_task.task_quartz_set.class_type
     * @mbg.generated Sat Nov 02 17:03:41 GMT+08:00 2019
     */
    public String getClassType() {
        return classType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column km_task.task_quartz_set.class_type
     *
     * @param classType the value for km_task.task_quartz_set.class_type
     *
     * @mbg.generated Sat Nov 02 17:03:41 GMT+08:00 2019
     */
    public void setClassType(String classType) {
        this.classType = classType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column km_task.task_quartz_set.start_plan_time
     *
     * @return the value of km_task.task_quartz_set.start_plan_time
     *
     * @mbg.generated Sat Nov 02 17:03:41 GMT+08:00 2019
     */
    public Date getStartPlanTime() {
        return startPlanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column km_task.task_quartz_set.start_plan_time
     *
     * @param startPlanTime the value for km_task.task_quartz_set.start_plan_time
     *
     * @mbg.generated Sat Nov 02 17:03:41 GMT+08:00 2019
     */
    public void setStartPlanTime(Date startPlanTime) {
        this.startPlanTime = startPlanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column km_task.task_quartz_set.next_plan_time
     *
     * @return the value of km_task.task_quartz_set.next_plan_time
     *
     * @mbg.generated Sat Nov 02 17:03:41 GMT+08:00 2019
     */
    public Date getNextPlanTime() {
        return nextPlanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column km_task.task_quartz_set.next_plan_time
     *
     * @param nextPlanTime the value for km_task.task_quartz_set.next_plan_time
     *
     * @mbg.generated Sat Nov 02 17:03:41 GMT+08:00 2019
     */
    public void setNextPlanTime(Date nextPlanTime) {
        this.nextPlanTime = nextPlanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column km_task.task_quartz_set.status
     *
     * @return the value of km_task.task_quartz_set.status
     *
     * @mbg.generated Sat Nov 02 17:03:41 GMT+08:00 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column km_task.task_quartz_set.status
     *
     * @param status the value for km_task.task_quartz_set.status
     *
     * @mbg.generated Sat Nov 02 17:03:41 GMT+08:00 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column km_task.task_quartz_set.plan_times
     *
     * @return the value of km_task.task_quartz_set.plan_times
     *
     * @mbg.generated Sat Nov 02 17:03:41 GMT+08:00 2019
     */
    public Integer getPlanTimes() {
        return planTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column km_task.task_quartz_set.plan_times
     *
     * @param planTimes the value for km_task.task_quartz_set.plan_times
     *
     * @mbg.generated Sat Nov 02 17:03:41 GMT+08:00 2019
     */
    public void setPlanTimes(Integer planTimes) {
        this.planTimes = planTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column km_task.task_quartz_set.create_time
     *
     * @return the value of km_task.task_quartz_set.create_time
     *
     * @mbg.generated Sat Nov 02 17:03:41 GMT+08:00 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column km_task.task_quartz_set.create_time
     *
     * @param createTime the value for km_task.task_quartz_set.create_time
     *
     * @mbg.generated Sat Nov 02 17:03:41 GMT+08:00 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column km_task.task_quartz_set.cron_id
     *
     * @return the value of km_task.task_quartz_set.cron_id
     *
     * @mbg.generated Sat Nov 02 17:03:41 GMT+08:00 2019
     */
    public Integer getCronId() {
        return cronId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column km_task.task_quartz_set.cron_id
     * @param cronId the value for km_task.task_quartz_set.cron_id
     * @mbg.generated Sat Nov 02 17:03:41 GMT+08:00 2019
     */
    public void setCronId(Integer cronId) {
        this.cronId = cronId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column km_task.task_quartz_set.cron_text
     * @return the value of km_task.task_quartz_set.cron_text
     * @mbg.generated Sat Nov 02 17:03:41 GMT+08:00 2019
     */
    public String getCronText() {
        return cronText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column km_task.task_quartz_set.cron_text
     * @param cronText the value for km_task.task_quartz_set.cron_text
     * @mbg.generated Sat Nov 02 17:03:41 GMT+08:00 2019
     */
    public void setCronText(String cronText) {
        this.cronText = cronText;
    }
}